name: Deploy To QiniuCloud

# Trigger
on:
  push:
    branches:
      - main

# Jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: hujiulong/action-qiniu-upload@master
      with:
        # Your qiniu access key, required.
        access_key: ${{ secrets.QINIU_ACCESS_KEY }}

        # Your qiniu secret key, required.
        secret_key: ${{ secrets.QINIU_SECRET_KEY }}

        # Bucket name, required.
        bucket: ${{ secrets.QINIU_BUCKET_NAME }}

        # The local directory (or file) you want to upload to bucket.
        # Default: './'
        source_dir: './public'

        # The directory inside of the bucket you want to upload to, namely key prefix prepended to dest file key.
        # Default: '/'
        dest_dir: '/'

        # Whether to ignore source maps.
        # Default: true
        ignore_source_map: true
